# Generated by Django 4.1.3 on 2022-11-02 19:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
