# Generated by Django 4.1.3 on 2022-11-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="message",
            field=models.TextField(help_text="< 100 chars", max_length=100),
        ),
    ]
